// Go SDK for the KUSANAGI(tm) framework (http://kusanagi.io)
// Copyright (c) 2016-2019 KUSANAGI S.L. All rights reserved.
//
// Distributed under the MIT license.
//
// For the full copyright and license information, please view the LICENSE
// file that was distributed with this source code.

package payload

import "github.com/kusanagi/kusanagi-sdk-go/traverse"

// DisableShortNames toggles the use of short names for payload properties
var DisableShortNames = false

// Payload field name aliase)s
var Aliases = traverse.Aliases{
	"action":         "a",
	"address":        "a",
	"arguments":      "a",
	"attributes":     "a",
	"available":      "a",
	"actions":        "ac",
	"array_format":   "af",
	"base_path":      "b",
	"body":           "b",
	"buffers":        "b",
	"busy":           "b",
	"cached":         "c",
	"call":           "c",
	"callback":       "c",
	"callee":         "c",
	"client":         "c",
	"code":           "c",
	"collection":     "c",
	"command":        "c",
	"commit":         "c",
	"component":      "c",
	"config":         "c",
	"count":          "c",
	"cpu":            "c",
	"caller":         "C",
	"calls":          "C",
	"complete":       "C",
	"command_reply":  "cr",
	"data":           "d",
	"datetime":       "d",
	"default_value":  "d",
	"disk":           "d",
	"path_delimiter": "d",
	"deferred_calls": "dc",
	"deprecated":     "D",
	"duration":       "D",
	"allow_empty":    "e",
	"end_time":       "e",
	"entity_path":    "e",
	"errors":         "e",
	"entity":         "E",
	"error":          "E",
	"enum":           "em",
	"exclusive_min":  "en",
	"exclusive_max":  "ex",
	"family":         "f",
	"field":          "f",
	"filename":       "f",
	"files":          "f",
	"format":         "f",
	"free":           "f",
	"fallback":       "F",
	"fallbacks":      "F",
	"fields":         "F",
	"gateway":        "g",
	"header":         "h",
	"headers":        "h",
	"http":           "h",
	"http_body":      "hb",
	"http_input":     "hi",
	"http_method":    "hm",
	"http_security":  "hs",
	"id":             "i",
	"idle":           "i",
	"in":             "i",
	"input":          "i",
	"interval":       "i",
	"items":          "i",
	"primary_key":    "k",
	"laddr":          "l",
	"level":          "l",
	"links":          "l",
	"memory":         "m",
	"message":        "m",
	"meta":           "m",
	"method":         "m",
	"mime":           "m",
	"min":            "mn",
	"multiple_of":    "mo",
	"max":            "mx",
	"name":           "n",
	"network":        "n",
	"optional":       "o",
	"origin":         "o",
	"out":            "o",
	"param":          "p",
	"params":         "p",
	"path":           "p",
	"pattern":        "p",
	"percent":        "p",
	"pid":            "p",
	"post_data":      "p",
	"properties":     "p",
	"protocol":       "p",
	"query":          "q",
	"raddr":          "r",
	"reads":          "r",
	"request":        "r",
	"required":       "r",
	"relations":      "r",
	"result":         "r",
	"rollback":       "r",
	"remote_calls":   "rc",
	"response":       "R",
	"return":         "rv",
	"schema":         "s",
	"schemes":        "s",
	"scope":          "s",
	"service":        "s",
	"shared":         "s",
	"size":           "s",
	"start_time":     "s",
	"status":         "s",
	"swap":           "s",
	"system":         "s",
	"tags":           "t",
	"terminate":      "t",
	"token":          "t",
	"total":          "t",
	"transactions":   "t",
	"type":           "t",
	"transport":      "T",
	"url":            "u",
	"used":           "u",
	"user":           "u",
	"unique_items":   "ui",
	"value":          "v",
	"version":        "v",
	"validate":       "V",
	"iowait":         "w",
	"writes":         "w",
	"timeout":        "x",
}
